In [12]:
import selenium
import pandas as pd
import requests
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import re
import time

### Q 1)

In [11]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
time.sleep(6)

# Empty Lists
rank_List = []
name_List = []
artist_List = []
uploadDate_List = []
views_List = []

#Find the elements
#Rank
try:
    ranks = driver.find_elements(By.XPATH, '//table[@class = "wikitable sortable jquery-tablesorter"][1]//tbody//tr//td[1]')
    for rank in ranks:
        rank_List.append(rank.text)
except NoSuchElementException:
    for i in range(0, 30):
        rank_List.append("-")

#Video Name
try:
    videoNames = driver.find_elements(By.XPATH, '//table[@class = "wikitable sortable jquery-tablesorter"][1]//tbody//tr//td[2]')
    for videoName in videoNames:
        name_List.append(videoName.text.split('"')[1])
except NoSuchElementException:
    for i in range(0, 30):
        name_List.append("-")
        
#Uploader
try:
    uploaders = driver.find_elements(By.XPATH, '//table[@class = "wikitable sortable jquery-tablesorter"][1]//tbody//tr//td[3]')
    for uploader in uploaders:
        artist_List.append(uploader.text)
except NoSuchElementException:
    for i in range(0, 30):
        artist_List.append("-")

#Upload Date
try:
    uploadDates = driver.find_elements(By.XPATH, '//table[@class = "wikitable sortable jquery-tablesorter"][1]//tbody//tr//td[5]')
    for uploadDate in uploadDates:
        uploadDate_List.append(uploadDate.text)
except NoSuchElementException:
    for i in range(0, 30):
        uploadDate_List.append("-")
        
#Views
try:
    views = driver.find_elements(By.XPATH, '//table[@class = "wikitable sortable jquery-tablesorter"][1]//tbody//tr//td[4]')
    for view in views:
        views_List.append(view.text)
except NoSuchElementException:
    for i in range(0, 30):
        views_List.append("-")
        
df = pd.DataFrame({"Rank" : rank_List, "Video Name" : name_List, "Artist" : artist_List, "Upload Date" : uploadDate_List, "Views in billlion" : views_List})
print(df)

   Rank                                 Video Name  \
0    1.                           Baby Shark Dance
1    2.                                  Despacito
2    3.                       Johny Johny Yes Papa
3    4.                                  Bath Song
4    5.                               Shape of You
5    6.                              See You Again
6    7.                Phonics Song with Two Words
7    8.                          Wheels on the Bus
8    9.                                Uptown Funk
9   10.  Learning Colors – Colorful Eggs on a Farm
10  11.                              Gangnam Style
11  12.   Masha and the Bear – Recipe for Disaster
12  13.                             Dame Tu Cosita
13  14.                                     Axel F
14  15.                                      Sugar
15  16.                                       Roar
16  17.                             Counting Stars
17  18.                                      Sorry
18  19.                        Baa Baa Black Sheep
19  20.                          Thinking Out Loud
20  21.           Waka Waka (This Time for Africa)
21  22.                                 Dark Horse
22  23.                                      Faded
23  24.                                    Perfect
24  25.                             Lakdi Ki Kathi
25  26.                                 Let Her Go
26  27.                             Girls Like You
27  28.          Humpty the train on a fruits ride
28  29.                                    Lean On
29  30.                                   Bailando

                                           Artist        Upload Date  \
0     Pinkfong Baby Shark - Kids' Songs & Stories      June 17, 2016
1                                      Luis Fonsi   January 12, 2017
2                                     LooLoo Kids    October 8, 2016
3                      Cocomelon – Nursery Rhymes        May 2, 2018
4                                      Ed Sheeran   January 30, 2017
5                                     Wiz Khalifa      April 6, 2015
6                                       ChuChu TV      March 6, 2014
7                      Cocomelon – Nursery Rhymes       May 24, 2018
8                                     Mark Ronson  November 19, 2014
9                                     Miroshka TV  February 27, 2018
10                                            Psy      July 15, 2012
11                                     Get Movies   January 31, 2012
12                                      El Chombo      April 5, 2018
13                                     Crazy Frog      June 16, 2009
14                                       Maroon 5   January 14, 2015
15                                     Katy Perry  September 5, 2013
16                                    OneRepublic       May 31, 2013
17                                  Justin Bieber   October 22, 2015
18                     Cocomelon – Nursery Rhymes      June 25, 2018
19                                     Ed Sheeran    October 7, 2014
20                                        Shakira       June 4, 2010
21                                     Katy Perry  February 20, 2014
22                                    Alan Walker   December 3, 2015
23                                     Ed Sheeran   November 9, 2017
24                                   Jingle Toons      June 14, 2018
25                                      Passenger      July 25, 2012
26                                       Maroon 5       May 31, 2018
27  Kiddiestv Hindi – Nursery Rhymes & Kids Songs   January 26, 2018
28                                    Major Lazer     March 22, 2015
29                               Enrique Iglesias     April 11, 2014

   Views in billlion
0              12.73
1               8.14
2               6.69
3               6.15
4               5.97
5               5.86
6               5.26
7               5.14
8               4.89
9               4.87
10              4.77
11              4.55
12              4.32
13              3.87
14              3.86
15              3.78
16              3.77
17              3.65
18              3.61
19              3.58
20              3.56
21              3.50
22              3.44
23              3.42
24              3.42
25              3.42
26              3.40
27              3.38
28              3.37
29              3.37

### Q 2)

In [21]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.bcci.tv/")
time.sleep(6)

#Navigate to International
international = driver.find_element(By.XPATH, '//li[@class = "nav-item"]//a[text() = "INTERNATIONAL"]')
international.click()
time.sleep(5)

#Select team as a India
allTeam = driver.find_element(By.XPATH, '//div[@class = "cSBDisplay ng-binding" and text() = "All Teams"]')
allTeam.click()
time.sleep(8)
india = driver.find_element(By.XPATH, '//div[text() = "india"]')
india.click()
time.sleep(5)

#Match title
name = driver.find_element(By.XPATH, '//h5[@class = "match-tournament-name ng-binding"]')
print("Match title = ",name.text )

#Place
stadium = driver.find_element(By.XPATH, '//span[@class = "ng-binding ng-scope"]')
stadiumName = stadium.text;
city = driver.find_element(By.XPATH, '//span[@class = "ng-binding"]')
cityName = city.text;
print("Place = ", stadiumName,cityName)

#Date
date = driver.find_element(By.XPATH, '//div[@class = "match-dates ng-binding"]')
print("Date = ", date.text)

#match-time
time = driver.find_element(By.XPATH, '//div[@class = "match-time no-margin ng-binding"]')
print("Time = ", time.text)

Match title =  ICC WORLD TEST CHAMPIONSHIP FINAL 2023
Place =  Kennington Oval, London
Date =  7 JUN 2023
Time =  3:30 PM IST

### Q 3)

In [11]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.statisticstimes.com/")
time.sleep(6)

#click on economy
economy = driver.find_element(By.XPATH, '//div[@class ="dropdown"][2]')
economy.click()

#Select the india in economy section
india = driver.find_element(By.XPATH, '//div[@class ="dropdown"][2] //div[@class="dropdown-content"]//a[text() = "India"]')
india.click()
time.sleep(10)

#Click on GDP of Indian States
gdp = driver.find_element(By.XPATH, '//a[contains(text(), "GDP of Indian states")]')
gdp.click()
time.sleep(8)

#Empty Lists
rank_List = []
state_List = []
GSDP_1819_List = []
GSDP_1920_List = []
share_List = []
GDPbln_List = []

#Rank

ranks = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "data1"]')
for rank in ranks:
    rank_List.append(rank.text)

#State
states = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "name"]')
for state in states:
    state_List.append(state.text)
    
#GSDP_1819
GSDP_1819 = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "data"][1]')
for i in GSDP_1819:
    GSDP_1819_List.append(i.text)
    
#GSDP_1920
GSDP_1920 = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "data sorting_1"]')
for i in GSDP_1920:
    GSDP_1920_List.append(i.text)
    
#Share
shares = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "data"][2]')
for share in shares:
    share_List.append(share.text)
    
#GDP Billion
GDPs = driver.find_elements(By.XPATH, '//div[@id = "table_id_wrapper"]//tbody//td[@class = "data"][3]')
for gdp in GDPs:
    GDPbln_List.append(gdp.text)
    
#DataFrame
df = pd.DataFrame({"Rank" : rank_List, "States" : state_List, "GSDP_1819" : GSDP_1819_List, "GSDP_1920" : GSDP_1920_List, "Share" : share_List, "GDp in billion" : GDPbln_List})

print(df)

   Rank                     States  GSDP_1819  GSDP_1920   Share  \
0     1                Maharashtra          -  2,632,792  13.94%
1     2                 Tamil Nadu  1,845,853  1,630,208   8.63%
2     3              Uttar Pradesh  1,687,818  1,584,764   8.39%
3     4                    Gujarat          -  1,502,899   7.96%
4     5                  Karnataka  1,631,977  1,493,127   7.91%
5     6                West Bengal  1,253,832  1,089,898   5.77%
6     7                  Rajasthan  1,020,989    942,586   4.99%
7     8             Andhra Pradesh    972,782    862,957   4.57%
8     9                  Telangana    969,604    861,031   4.56%
9    10             Madhya Pradesh    906,672    809,592   4.29%
10   11                     Kerala          -    781,653   4.14%
11   12                      Delhi    856,112    774,870   4.10%
12   13                    Haryana    831,610    734,163   3.89%
13   14                      Bihar    611,804    530,363   2.81%
14   15                     Punjab    574,760    526,376   2.79%
15   16                     Odisha    521,275    487,805   2.58%
16   17                      Assam          -    315,881   1.67%
17   18               Chhattisgarh    329,180    304,063   1.61%
18   19                  Jharkhand    328,598    297,204   1.57%
19   20                Uttarakhand          -    245,895   1.30%
20   21            Jammu & Kashmir          -    155,956   0.83%
21   22           Himachal Pradesh    165,472    153,845   0.81%
22   23                        Goa     80,449     73,170   0.39%
23   24                    Tripura     55,984     49,845   0.26%
24   25                 Chandigarh          -     42,114   0.22%
25   26                 Puducherry     38,253     34,433   0.18%
26   27                  Meghalaya     36,572     33,481   0.18%
27   28                     Sikkim     32,496     28,723   0.15%
28   29                    Manipur     31,790     27,870   0.15%
29   30                   Nagaland          -     27,283   0.14%
30   31          Arunachal Pradesh          -     24,603   0.13%
31   32                    Mizoram     26,503     22,287   0.12%
32   33  Andaman & Nicobar Islands          -          -       -

   GDp in billion
0         399.921
1         247.629
2         240.726
3         228.290
4         226.806
5         165.556
6         143.179
7         131.083
8         130.791
9         122.977
10        118.733
11        117.703
12        111.519
13         80.562
14         79.957
15         74.098
16         47.982
17         46.187
18         45.145
19         37.351
20         23.690
21         23.369
22         11.115
23          7.571
24          6.397
25          5.230
26          5.086
27          4.363
28          4.233
29          4.144
30          3.737
31          3.385
32              -

### Q 4)

In [14]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://github.com/")
time.sleep(6)

#click on Open source
openSource = driver.find_element(By.XPATH, '//li//button[contains(text(), "Open Source")]')
openSource.click()

#Click on Trending
trending = driver.find_element(By.XPATH, '//li//a[contains(text(), "Trending")]')
trending.click()
time.sleep(10)

#Store repository addresses
links_List = []
links = driver.find_elements(By.XPATH, '//h2[@class ="h3 lh-condensed"]//a')
for link in links:
    links_List.append(link.get_attribute("href"))
    
title_List = []
description_List = []
contriCount_List = []
language_List = []

#scrap the details
for link in links_List:
    driver.get(link)
    time.sleep(6)
    
    #Title
    try:
        title = driver.find_element(By.XPATH, '//strong[@class = "mr-2 flex-self-stretch"]//a')
        title_List.append(title.text)
    except NoSuchElementException:
        title_List.append("-")
        
    #description
    try:
        descriptiont = driver.find_element(By.XPATH, '//p[@class = "f4 my-3"]')
        description_List.append(descriptiont.text)
    except NoSuchElementException:
        description_List.append("-")
        
    #contributors
    try:
        contributor = driver.find_element(By.XPATH, '//a[@class = "Link--primary no-underline"]//span[@class = "Counter"]')
        contriCount_List.append(contributor.text)
    except:
        contriCount_List.append("-")
        
    #Languages
    try:
        language = driver.find_element(By.XPATH, '//span[@class = "color-fg-default text-bold mr-1"][1]')
        language_List.append(language.text)
    except:
        language_List.append("-")
        
df = pd.DataFrame({"Repo Title" : title_List, "Descrtiption" : description_List, "Contributers Count" : contriCount_List, "Language" : language_List})
print(df)

                                   Repo Title  \
0                                    gpt4free
1                                    AudioGPT
2                              Track-Anything
3                                       tabby
4                                   chart-gpt
5                            swift-foundation
6                                   databerry
7                                          IF
8   Segment-Everything-Everywhere-All-At-Once
9                                    WizardLM
10                      QQFlacMusicDownloader
11                                    awesome
12                              ai-collection
13                                 PentestGPT
14                                hyperswitch
15                                  dndserver
16                            NeMo-Guardrails
17                                    loopgpt
18                                     skyagi
19                 Auto-GPT-MetaTrader-Plugin
20                              LLaMA-Adapter
21                                     Motrix
22                                     trader
23                                     WebGPT
24                                    angular

                                         Descrtiption Contributers Count  \
0   decentralising the Ai Industry, just some lang...                 37
1   AudioGPT: Understanding and Generating Speech,...
2   Track-Anything is a flexible and interactive t...
3                    A terminal for a more modern age                175
4         AI tool to build charts based on text input
5                              The Foundation project
6   The no-code platform for connecting custom dat...
7                                                   -                  2
8   Official implementation of the paper "Segment ...
9   WizardLM: Empowering Large Pre-Trained Languag...
10                                [秋城落叶] QQ 音乐源无损歌曲下载
11  😎 Awesome lists about all kinds of interesting...                  5
12  The Generative AI Landscape - A Collection of ...
13           A GPT-empowered penetration testing tool                  4
14  An Open Source Financial Switch to make Paymen...                 11
15  Dark and Darker private server implementation ...                  1
16  NeMo Guardrails is an open-source toolkit for ...
17                         Modular Auto-GPT Framework                  2
18  SkyAGI: Emerging human-behavior simulation cap...                 20
19  The AutoGPT MetaTrader Plugin is a software to...                  2
20  Fine-tuning LLaMA to follow Instructions withi...                  1
21                  A full-featured download manager.                 18
22                                               交易模块
23  Run GPT model on the browser with WebGPU. An i...                  5
24                The modern web developer’s platform                268

      Language
0       Python
1       Python
2       Python
3   TypeScript
4   TypeScript
5        Swift
6   TypeScript
7       Python
8       Python
9       Python
10      Python
11           -
12           -
13        HTML
14        Rust
15      Python
16      Python
17      Python
18      Python
19      Python
20      Python
21  JavaScript
22      Python
23  JavaScript
24  TypeScript

### Q 5)

In [13]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.billboard.com/")
time.sleep(6)

#Click on menu
menu = driver.find_element(By.XPATH, '//button[@class = "o-icon-button lrv-a-unstyle-button lrv-a-unstyle-link lrv-u-cursor-pointer lrv-u-flex js-MegaMenu-Trigger lrv-u-color-grey:hover lrv-a-hover-effect"]')
menu.click()
time.sleep(8)

#expand charts
expand = driver.find_element(By.XPATH, '//button[@class = "lrv-js-MobileHeightToggle-trigger lrv-a-unstyle-button a-hidden@desktop u-display-inline-flex lrv-u-margin-l-auto lrv-u-padding-a-1"][2]')
expand.click()
time.sleep(20)

#hot 100
hot100 = driver.find_element(By.XPATH, '//a[contains(text() ,"Hot 100")]')
hot100.click()
time.sleep(10)

TimeoutException: Message: timeout: Timed out receiving message from renderer: 241.046
  (Session info: chrome=112.0.5615.138)
Stacktrace:
Backtrace:
	GetHandleVerifier [0x0115DCE3+50899]
	(No symbol) [0x010EE111]
	(No symbol) [0x00FF5588]
	(No symbol) [0x00FE83BF]
	(No symbol) [0x00FE820C]
	(No symbol) [0x00FE6F06]
	(No symbol) [0x00FE778A]
	(No symbol) [0x00FF06F5]
	(No symbol) [0x00FFAB28]
	(No symbol) [0x00FFD4D6]
	(No symbol) [0x00FE7AE3]
	(No symbol) [0x00FFA9F1]
	(No symbol) [0x0104E219]
	(No symbol) [0x0103B6F6]
	(No symbol) [0x01017708]
	(No symbol) [0x0101886D]
	GetHandleVerifier [0x013C3EAE+2566302]
	GetHandleVerifier [0x013F92B1+2784417]
	GetHandleVerifier [0x013F327C+2759788]
	GetHandleVerifier [0x011F5740+672048]
	(No symbol) [0x010F8872]
	(No symbol) [0x010F41C8]
	(No symbol) [0x010F42AB]
	(No symbol) [0x010E71B7]
	BaseThreadInitThunk [0x75920099+25]
	RtlGetAppContainerNamedObjectPath [0x76FD7B6E+286]
	RtlGetAppContainerNamedObjectPath [0x76FD7B3E+238]

### Q 6)

In [15]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")
time.sleep(6)

#Empty lists
bookName_List = []
authorName_List = []
volume_List = []
publisher_List = []
genre_List = []

#Scrap the details
#Name
books_Name = driver.find_elements(By.XPATH, '//table[@class = "in-article sortable"]//tbody//tr//td[1]')
for book in books_Name:
    bookName_List.append(book.text)
    
#author
authors = driver.find_elements(By.XPATH, '//table[@class = "in-article sortable"]//tbody//tr//td[2]')
for author in authors:
    authorName_List.append(author.text)
    
#volume
volumes = driver.find_elements(By.XPATH, '//table[@class = "in-article sortable"]//tbody//tr//td[3]')
for volume in volumes:
    volume_List.append(volume.text)
    
#Publisher
publishers = driver.find_elements(By.XPATH, '//table[@class = "in-article sortable"]//tbody//tr//td[4]')
for publisher in publishers:
    publisher_List.append(publisher.text)
    
#genre
genres = driver.find_elements(By.XPATH, '//table[@class = "in-article sortable"]//tbody//tr//td[5]')
for genre in genres:
    genre_List.append(genre.text)
    
df = pd.DataFrame({"Book Name" : bookName_List, "Author" : authorName_List, "Volume" : volume_List, "Publisher" : publisher_List, "Genre" : genre_List})
df

,Book Name,Author,Volume,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House
...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin

### Q 7)

In [26]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.imdb.com/list/ls095964455/")
time.sleep(6)

#Empty Lists
name_List = []
yearSpan_List = []
genre_List = []
runTime_List = []
ratings_List = []
voters_List = []

#get all series
items = WebDriverWait(driver, 20).until(EC.presence_of_all_elements_located((By.XPATH, '//div[@class = "lister-item mode-detail"]')))

#All details to be filled in list
for item in items:
    #Name
    try:
        name = item.find_element(By.XPATH, './/h3[@class = "lister-item-header"]//a')
        name_List.append(name.text)
    except NoSuchElementException:
        name_List.append("-")
    
    #Year
    try:
        year = item.find_element(By.XPATH, './/h3[@class = "lister-item-header"]//span[@class = "lister-item-year text-muted unbold"]')
        yearSpan_List.append(year.text)
    except NoSuchElementException:
        yearSpan_List.append("-")
        
    #genre
    try:
        genre = item.find_element(By.XPATH, './/span[@class = "genre"]')
        genre_List.append(genre.text)
    except NoSuchElementException:
        genre_List.append("-")
        
    #runtime
    try:
        runtime = item.find_element(By.XPATH, './/span[@class = "runtime"]')
        runTime_List.append(runtime.text)
    except NoSuchElementException:
        runTime_List.append("-")
        
    #ratings
    try:
        rating = item.find_element(By.XPATH, './/div[@class = "ipl-rating-star small"]//span[@class = "ipl-rating-star__rating"]')
        ratings_List.append(rating.text)
    except NoSuchElementException:
        ratings_List.append("-")
        
    #Voters
    try:
        voters = item.find_element(By.XPATH, './/span[@name = "nv"]')
        voters_List.append(voters.text)
    except NoSuchElementException:
        voters_List.append("-")
        
df = pd.DataFrame({"Name" : name_List, "Years Span" : yearSpan_List, "Genre" : genre_List, "Runtime" : runTime_List, "Ratings" : ratings_List, "Voters" : voters_List})
df

,Name,Years Span,Genre,Runtime,Ratings,Voters
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,155,015"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,236,783"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,023,782"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"301,228"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"260,215"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"51,443"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"63,486"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"207,006"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7,"42,997"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"256,744"

### Q8)

In [31]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://archive.ics.uci.edu/")
time.sleep(6)

#click on all data set
allDataset = driver.find_element(By.XPATH, '//span[@class = "whitetext"]//b[text()= "View ALL Data Sets"]')
allDataset.click()
time.sleep(8)

#Empty Lists
datasetName_List = []
datatype_List = []
task_List = []
attributestype_List = []
instances_List = []
attributes_List = []
years_List = []

#Scrap all rows
rows = driver.find_elements(By.XPATH, '//table[@cellpadding = "5" and @border = "1"]/tbody/tr')

#Scrap Data from each row
for row in rows:
    #Names
    try:
        name = row.find_element(By.XPATH, './td//p[@class = "normal"]//a')
        datasetName_List.append(name.text)
    except NoSuchElementException:
        datasetName_List.append("-")
        
    #Type
    try:
        datatype = row.find_element(By.XPATH, './td[2]/p[@class = "normal"]')
        datatype_List.append(datatype.text.split('&')[0])
    except NoSuchElementException:
        datatype_List.append("-")
        
    #task
    try:
        task = row.find_element(By.XPATH, './td[3]/p[@class = "normal"]')
        task_List.append(task.text.split('&')[0])
    except NoSuchElementException:
        task_List.append("-")
    
    #attributes type
    try:
        attribute = row.find_element(By.XPATH, './td[4]/p[@class = "normal"]')
        attributestype_List.append(attribute.text.split('&')[0])
    except NoSuchElementException:
        attributestype_List.append("-")
        
    #Instances
    try:
        instance = row.find_element(By.XPATH, './td[5]/p[@class = "normal"]')
        instances_List.append(instance.text.split('&')[0])
    except NoSuchElementException:
        instances_List.append("-")
        
    #attribute
    try:
        attribute = row.find_element(By.XPATH, './td[6]/p[@class = "normal"]')
        attributes_List.append(attribute.text.split('&')[0])
    except NoSuchElementException:
        attributes_List.append("-")
        
    #years
    try:
        year = row.find_element(By.XPATH, './td[7]/p[@class = "normal"]')
        years_List.append(year.text.split('&')[0])
    except NoSuchElementException:
        years_List.append("-")
        
df = pd.DataFrame({"DataSet Name" : datasetName_List, "Data Type" : datatype_List, "Task" : task_List, "Attribute Type" : attributestype_List, "Instance" : instances_List, "Attributes" : attributes_List, "Years" : years_List})
df

,DataSet Name,Data Type,Task,Attribute Type,Instance,Attributes,Years
0,-,-,-,-,-,-,-
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
...,...,...,...,...,...,...,...
618,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
619,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
620,Maternal Health Risk Data Set,,Classification,,1014,7,2020
621,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
622,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

### Q 9)

In [37]:
#Browse the website
driver = webdriver.Chrome(r"E:\Internship\chromedriver.exe")
driver.get("https://www.naukri.com/hr-recruiters-consultants")
time.sleep(6)

#Type in search bar
search = driver.find_element(By.XPATH, '//input[@name = "qp"]')
search.send_keys("Data Science")

#click on search
btnSearch = driver.find_element(By.XPATH, '//button[@id = "qsbFormBtn"]')
btnSearch.click()
time.sleep(6)

#Empty Lists
name_List = []
designation_List = []
company_List = []
skills_List = []
location_List = []

#scrap the recruites
recruiters = driver.find_elements(By.XPATH, '//div[@class = "recInfo"]')

#Scrap all details 1 by 1
for recruiter in recruiters:
    #Name
    try:
        name = recruiter.find_element(By.XPATH, './/span[@class = "fl ellipsis"]')
        name_List.append(name.text)
    except NoSuchElementException:
        name_List.append("-")
        
    #Designation
    try:
        designation = recruiter.find_element(By.XPATH, './/span[@class = "ellipsis clr"]')
        designation_List.append(designation.text)
    except NoSuchElementException:
        designation_List.append("-")
        
    #comapny
    try:
        company = recruiter.find_element(By.XPATH, './/a[@class = "ellipsis"][2]')
        company_List.append(company.text)
    except NoSuchElementException:
        company_List.append("-")
        
    #Skills
    try:
        skill = recruiter.find_element(By.XPATH, './/div[@class = "hireSec highlightable"]')
        skills_List.append(skill.text)
    except NoSuchElementException:
        skills_List.append("-")
        
    #location
    try:
        location = recruiter.find_element(By.XPATH, './/small[@class  = "ellipsis"]')
        location_List.append(location.text)
    except NoSuchElementException:
        location_List.append("-")
    
df = pd.DataFrame({"Name" : name_List, "Designation" : designation_List, "Comapny" : company_List, "Skills" : skills_List, "Location" : location_List})
df

,Name,Designation,Comapny,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
14,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa...",Gurgaon
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",-
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
32,Dhruv Dev Dubey,Company Recruitment Head,NETAPS FOUNDATION,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,Avnish Mishra,Senior Technical &amp; Corporate Recruiter,RMS Risk Management Solutions,"Data Science, Machine Learning, Deep Learning,...",Noida
34,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
35,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad / Secunderabad
36,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
37,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
38,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
39,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
40,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
41,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
42,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
43,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
44,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
45,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
46,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
47,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
48,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
49,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai